### ISSUE TITLE
doc: Useless ref-index.so

### ISSUE THREAD

**Issue by jtxa** [sierrafoxtrot/srecord#21]
The content of the generated `ref-index.so` is not used.
Even if it's empty, the PDF is identical: same size, same text content, just some bytes are different at the end, some of them being a unique identifier
This is a regression of version 1.65.

Found a small extra problem: the last content page in the PDF has number 1000. But this was introduced a long time age (I checked 1.50 and it was already there)

**Comment by sierrafoxtrot** [comment]
I've removed ref_index.so. Page 1000 looks like a weekend job though

**Comment by jtxa** [comment]
Just to make sure, that my issue was understood correctly (I should have added a few sentences more):
The index has no effect today, but in v1.64 it really appended an index (or so called *Table of Contents*).

If the removal of the index in v1.65 was on purpose, then removing the script completely is the right solution.

**Comment by marcows** [comment]
See also comments in 4ae29d8543ac8f6296a79fc7fad42aa62941c6fb

**Comment by jtxa** [comment]
Yes, that's about the same topic.
So the first page of the index is now at page 3 (a good position), and the rest is missing,

I don't how useful the index is at all, for printed books yes, but today....? Especially as these PDFs have no hyperlinks on page numbers.

**Comment by marcows** [comment]
> I don't how useful the index is at all

See short discussion about this at https://github.com/sierrafoxtrot/srecord/pull/11#discussion_r1005509263

**Comment by sierrafoxtrot** [comment]
I don't see any harm leaving it it and believe it or not, I actually do have a use for the printed copy (although I'm probably in the minority). Hyperlinks would be a nice addition though. I'll look into how that might be done.
